# Generated by Django 5.0 on 2024-01-31 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopSkate', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='state',
            new_name='country',
        ),
        migrations.AlterField(
            model_name='product',
            name='digital',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
